'use strict';
// Landing-page strings (server-side rendered). EN is the canonical fallback.
// 2 locales → no language selector; resolved silently from the zl-lang cookie
// then Accept-Language, defaulting to en.

const STR = {
  en: {
    tagline: 'Your phone is the trackpad.',
    lede: 'Control your computer’s mouse and keyboard from any phone — over your local Wi-Fi, or end-to-end encrypted from anywhere through remote.zlef.fr. No app store, no account required.',
    cta_download: 'Download the agent',
    cta_how: 'How it works',
    badge_e2ee: 'End-to-end encrypted',
    badge_noinstall: 'No app to install on your phone',
    badge_cross: 'Linux · Windows · macOS',

    how_title: 'How it works',
    how_1_t: '1 · Run the agent on your computer',
    how_1_b: 'A single portable binary. It injects mouse and keyboard events into your OS — nothing else runs in the background.',
    how_2_t: '2 · Scan the QR code',
    how_2_b: 'The agent shows a QR. Scan it with your phone’s camera to open the remote in your mobile browser. Nothing to install on the phone.',
    how_3_t: '3 · Take control',
    how_3_b: 'Use the touch trackpad, tap to click, two-finger scroll, and a full keyboard with media keys and shortcuts.',

    modes_title: 'Two ways to connect',
    mode_lan_t: 'Local network',
    mode_lan_b: 'The agent runs its own tiny web server. Your phone connects straight to your computer over Wi-Fi — traffic never leaves your network. Lowest latency.',
    mode_remote_t: 'Remote (remote.zlef.fr)',
    mode_remote_b: 'Away from home? The agent pairs through this relay using a 6-character room code. Every keystroke and movement is encrypted on your phone and only decrypted by your computer — the relay forwards opaque bytes and can never read them.',

    e2ee_title: 'The relay can’t see your input',
    e2ee_b: 'A random 256-bit key is generated by the agent and embedded only in the QR code’s URL fragment — the part after “#” that browsers never send to a server. Your phone reads it locally. Every frame is sealed with AES-256-GCM. remote.zlef.fr only ever sees a room code and ciphertext.',

    dl_title: 'Download',
    dl_b: 'Pick your platform. The agent is a self-contained executable — run it, scan, done.',
    dl_linux: 'Linux',
    dl_win: 'Windows',
    dl_mac: 'macOS',
    dl_source: 'Build from source',
    dl_soon: 'Build from source',
    dl_arch: '64-bit',
    dl_note: 'On first run the agent asks whether to expose itself on your local network or pair through the encrypted relay.',

    feat_title: 'What’s inside',
    feat_1_t: 'Precision trackpad',
    feat_1_b: 'Relative pointer movement with acceleration, tap-to-click, right-click, drag-lock and two-finger scroll.',
    feat_2_t: 'Full keyboard',
    feat_2_b: 'Type naturally, send special keys, modifier combos (Ctrl/Alt/Cmd) and OS shortcuts.',
    feat_3_t: 'Media controls',
    feat_3_b: 'Volume, mute, play/pause and track skip — turn your phone into a remote for the couch.',
    feat_4_t: 'Open & auditable',
    feat_4_b: 'No telemetry, no account on the relay. The crypto is standard WebCrypto + Go stdlib. Source is public.',

    footer_made: 'A zlef.fr project',
    open_remote: 'Open the remote',
    nav_features: 'Features',
    nav_download: 'Download',
  },
  fr: {
    tagline: 'Votre téléphone devient le trackpad.',
    lede: 'Contrôlez la souris et le clavier de votre ordinateur depuis n’importe quel téléphone — sur votre Wi-Fi local, ou chiffré de bout en bout où que vous soyez via remote.zlef.fr. Sans store, sans compte.',
    cta_download: 'Télécharger l’agent',
    cta_how: 'Comment ça marche',
    badge_e2ee: 'Chiffré de bout en bout',
    badge_noinstall: 'Rien à installer sur le téléphone',
    badge_cross: 'Linux · Windows · macOS',

    how_title: 'Comment ça marche',
    how_1_t: '1 · Lancez l’agent sur l’ordinateur',
    how_1_b: 'Un seul exécutable portable. Il injecte les événements souris et clavier dans votre système — rien d’autre ne tourne en arrière-plan.',
    how_2_t: '2 · Scannez le QR code',
    how_2_b: 'L’agent affiche un QR code. Scannez-le avec l’appareil photo pour ouvrir la télécommande dans votre navigateur mobile. Rien à installer.',
    how_3_t: '3 · Prenez le contrôle',
    how_3_b: 'Trackpad tactile, tap pour cliquer, défilement à deux doigts, et un clavier complet avec touches média et raccourcis.',

    modes_title: 'Deux façons de se connecter',
    mode_lan_t: 'Réseau local',
    mode_lan_b: 'L’agent lance son propre petit serveur web. Le téléphone se connecte directement à l’ordinateur en Wi-Fi — le trafic ne quitte jamais votre réseau. Latence minimale.',
    mode_remote_t: 'À distance (remote.zlef.fr)',
    mode_remote_b: 'Loin de chez vous ? L’agent s’appaire via ce relais avec un code de salon à 6 caractères. Chaque frappe et chaque mouvement est chiffré sur le téléphone et déchiffré uniquement par votre ordinateur — le relais ne transporte que des octets opaques.',

    e2ee_title: 'Le relais ne voit rien de vos saisies',
    e2ee_b: 'Une clé aléatoire de 256 bits est générée par l’agent et placée uniquement dans le fragment d’URL du QR code — la partie après « # » que les navigateurs n’envoient jamais au serveur. Le téléphone la lit localement. Chaque trame est scellée en AES-256-GCM. remote.zlef.fr ne voit qu’un code de salon et du chiffré.',

    dl_title: 'Téléchargement',
    dl_b: 'Choisissez votre plateforme. L’agent est un exécutable autonome — lancez, scannez, c’est parti.',
    dl_linux: 'Linux',
    dl_win: 'Windows',
    dl_mac: 'macOS',
    dl_source: 'Compiler depuis les sources',
    dl_soon: 'Compiler depuis les sources',
    dl_arch: '64-bit',
    dl_note: 'Au premier lancement, l’agent demande s’il doit s’exposer sur votre réseau local ou s’appairer via le relais chiffré.',

    feat_title: 'Ce qu’il contient',
    feat_1_t: 'Trackpad précis',
    feat_1_b: 'Mouvement relatif avec accélération, tap pour cliquer, clic droit, verrou de glissement et défilement à deux doigts.',
    feat_2_t: 'Clavier complet',
    feat_2_b: 'Tapez naturellement, envoyez les touches spéciales, les combos (Ctrl/Alt/Cmd) et les raccourcis système.',
    feat_3_t: 'Contrôles média',
    feat_3_b: 'Volume, muet, lecture/pause et piste suivante — votre téléphone devient la télécommande du canapé.',
    feat_4_t: 'Ouvert et auditable',
    feat_4_b: 'Aucune télémétrie, aucun compte sur le relais. La crypto est standard (WebCrypto + Go stdlib). Le code est public.',

    footer_made: 'Un projet zlef.fr',
    open_remote: 'Ouvrir la télécommande',
    nav_features: 'Fonctions',
    nav_download: 'Télécharger',
  },
};

function pickLang(req) {
  const cookie = (req.headers.cookie || '');
  const m = cookie.match(/(?:^|;\s*)zl-lang=(\w{2})/);
  if (m && STR[m[1]]) return m[1];
  const al = (req.headers['accept-language'] || '').toLowerCase();
  if (al.startsWith('fr')) return 'fr';
  return 'en';
}

function dict(lang) { return STR[lang] || STR.en; }

module.exports = { STR, pickLang, dict };
